name: flame_canvas
description: (Experimental) Flame Visual Editor
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  change_case: ^2.1.0
  equatable: ^2.0.5
  flame: ^1.17.0
  flame_bloc: ^1.12.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  path: ^1.9.0
  uuid: ^4.4.0

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
